name: CI intergration testing

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest  # Runs the job on the latest windows image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # - name: Lint code
    #   run: npm run lint


    # .github/workflows/ci.yml
# name: CI Pipeline

# on: [push, pull_request]

# jobs:
#   build-and-test:
#     runs-on: windows-latest  # Runs the job on the latest windows image

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '16'

#     - name: Install Dependencies
#       run: npm install

#     - name: Generate Tests
#       run: node generate-tests.js # Your script for test generation

#     - name: Run Tests
#       run: npm test
